"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

import { Metric, ViewState, inputClass, primaryButtonClass } from "@/components/experiments/shared";
import { Breadcrumbs } from "@/components/product-context";
import { CopyableReference } from "@/components/workflow-controls";
import { createBisectionSession, getRegressionCheck, listBisectionSessions, type BisectionSessionSummary, type RegressionCheck } from "@/lib/regression-api";
import { bisectionEligibility, classificationLabel, formatEffect, formatOptionalMetric, formatPassRateDrop } from "@/lib/regression-ui";
import { formatTimestamp } from "@/lib/trace-explorer";

import { EvidenceBadge, Field, FullSha } from "./shared";

export function RegressionCheckDetail({ checkId }: { checkId: string }) {
  const router = useRouter(); const [check, setCheck] = useState<RegressionCheck | null>(null); const [sessions, setSessions] = useState<BisectionSessionSummary[]>([]); const [repositoryPath, setRepositoryPath] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [actionError, setActionError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [retry, setRetry] = useState(0);
  useEffect(() => { const controller = new AbortController(); Promise.all([getRegressionCheck(checkId, controller.signal), listBisectionSessions(checkId, controller.signal)]).then(([nextCheck, page]) => { setCheck(nextCheck); setSessions(page.items); setError(null); }).catch((reason: unknown) => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : "Unable to load regression check."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [checkId, retry]);
  async function plan(event: React.FormEvent) { event.preventDefault(); if (!repositoryPath.trim()) { setActionError("Local repository path is required."); return; } setBusy(true); setActionError(null); try { const session = await createBisectionSession({ regression_check_id: checkId, repository_path: repositoryPath.trim() }); router.push(`/regressions/bisections/${encodeURIComponent(session.id)}`); } catch (reason) { setActionError(reason instanceof Error ? reason.message : "Unable to plan the bisection session."); } finally { setBusy(false); } }
  if (loading) return <div aria-busy="true" aria-label="Loading regression check" className="mx-auto h-[36rem] max-w-[90rem] animate-pulse border bg-surface" />;
  if (error || !check) return <ViewState title="Couldn’t load regression check" detail={error ?? "Regression check not found."} role="alert" headingLevel="h1"><button onClick={() => { setLoading(true); setRetry((value) => value + 1); }} className={`mt-4 ${primaryButtonClass}`}>Retry</button></ViewState>;
  const eligibility = bisectionEligibility(check); const baselineSha = typeof check.baseline_provenance.git_commit_sha === "string" ? check.baseline_provenance.git_commit_sha : null; const candidateSha = typeof check.candidate_provenance.git_commit_sha === "string" ? check.candidate_provenance.git_commit_sha : null;
  return <div className="mx-auto max-w-[90rem]"><Breadcrumbs items={[{ label: "Regressions", href: "/regressions" }, { label: "Experiment run", href: `/experiments/runs/${encodeURIComponent(check.experiment_run_id)}` }, { label: "Regression check" }]} /><header className="border-b pb-6"><p className="font-mono text-xs font-semibold tracking-[0.16em] text-accent">REGRESSION / CHECK</p><div className="mt-3 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Canonical regression evidence</h1><EvidenceBadge value={check.classification} /></div><div className="mt-2 text-muted"><CopyableReference value={check.id} label="regression check ID" /></div><p className="mt-4 max-w-4xl text-sm leading-6 text-muted">{classificationLabel(check.classification)} is a policy-defined observation over persisted experiment evidence. It does not identify a causal Git commit.</p></header>
    <section aria-labelledby="context-title" className="mt-7"><h2 id="context-title" className="text-xl font-semibold">Frozen check context</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6"><Metric label="Policy" value={check.policy_name} /><Metric label="Practical threshold" value={formatPassRateDrop(check.minimum_pass_rate_drop)} /><Metric label="Minimum sample" value={check.minimum_sample_size} /><Metric label="Baseline" value={`Variant ${check.baseline_variant}`} /><Metric label="Candidate" value={`Variant ${check.candidate_variant}`} /><Metric label="Created" value={formatTimestamp(check.created_at)} /></div><dl className="mt-4 grid gap-3 border bg-surface p-4 sm:grid-cols-2"><div className="min-w-0"><dt className="text-xs font-semibold text-muted">Baseline Git SHA</dt><dd className="mt-1">{baselineSha ? <FullSha value={baselineSha} /> : "Not supplied"}</dd></div><div className="min-w-0"><dt className="text-xs font-semibold text-muted">Candidate Git SHA</dt><dd className="mt-1">{candidateSha ? <FullSha value={candidateSha} /> : "Not supplied"}</dd></div></dl></section>
    <section aria-labelledby="finding-title" className="mt-8"><h2 id="finding-title" className="text-xl font-semibold">Per-condition findings</h2><p className="mt-1 text-sm leading-6 text-muted">All values below are persisted backend values; no statistics are calculated or recomputed in this browser.</p><div className="mt-4 grid gap-4 lg:grid-cols-2">{check.findings.map((finding) => <article key={finding.condition_position} className="min-w-0 border bg-surface p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{finding.definition_name}</h3><p className="mt-1 font-mono text-xs text-muted">Condition {finding.condition_position} · {finding.evaluator_kind}</p></div><EvidenceBadge value={finding.classification} /></div><dl className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3"><Value label="Sample size" value={formatOptionalMetric(finding.sample_size)} /><Value label="Baseline pass rate" value={finding.baseline_pass_rate === null ? "Not available" : `${(finding.baseline_pass_rate * 100).toFixed(1)}%`} /><Value label="Candidate pass rate" value={finding.candidate_pass_rate === null ? "Not available" : `${(finding.candidate_pass_rate * 100).toFixed(1)}%`} /><Value label="Candidate-minus-baseline difference" value={formatEffect(finding.candidate_minus_baseline)} /><Value label="Paired interval" value={`${formatEffect(finding.confidence_interval_lower)} to ${formatEffect(finding.confidence_interval_upper)}`} /><Value label="McNemar p-value" value={formatOptionalMetric(finding.p_value)} /></dl><p className="mt-4 text-xs leading-5 text-muted">Threshold: {formatPassRateDrop(finding.minimum_pass_rate_drop)}; classification: {classificationLabel(finding.classification)}.{finding.source_ineligible_reason ? ` Source reason: ${finding.source_ineligible_reason}.` : ""}</p></article>)}</div></section>
    <section aria-labelledby="planning-title" className="mt-8 border bg-surface p-5"><h2 id="planning-title" className="text-xl font-semibold">Plan local Git bisection</h2><p className="mt-1 max-w-4xl text-sm leading-6 text-muted">Planning verifies that the baseline is an ancestor of the candidate, inspects the repository read-only, and freezes full SHAs. Branch movement after planning cannot change the session.</p>{eligibility.eligible ? <form onSubmit={plan} className="mt-5 max-w-3xl"><Field label="Local repository path" hint="The API process must be able to read this local path."><input value={repositoryPath} onChange={(event) => setRepositoryPath(event.target.value)} maxLength={2_048} required className={`${inputClass} font-mono`} /></Field>{actionError && <p role="alert" className="mt-3 break-words border border-red-200 bg-red-50 p-3 text-sm text-red-900">{actionError}</p>}<button disabled={busy} className={`mt-4 ${primaryButtonClass}`}>{busy ? "Planning…" : "Create frozen bisection session"}</button></form> : <p role="status" className="mt-4 border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950">{eligibility.reason}</p>}
      {sessions.length > 0 && <ul className="mt-6 divide-y border" aria-label="Bisection sessions">{sessions.map((session) => <li key={session.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div className="min-w-0"><Link href={`/regressions/bisections/${encodeURIComponent(session.id)}`} className="font-semibold text-accent hover:underline">Open frozen session</Link><p className="mt-1 break-all font-mono text-xs text-muted">{session.id}</p></div><span className="text-sm">{session.commit_count} commits</span></li>)}</ul>}
    </section>
  </div>;
}

function Value({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><dt className="text-xs font-semibold text-muted">{label}</dt><dd className="mt-1 break-words font-mono text-sm">{value}</dd></div>; }
