"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";

import { inputClass, primaryButtonClass, ViewState } from "@/components/experiments/shared";
import { PageHeader } from "@/components/product-context";
import { createRegressionCheck, createRegressionPolicy, listRegressionChecks, listRegressionPolicies, type RegressionCheckSummary, type RegressionPolicy, type VariantKey } from "@/lib/regression-api";
import { buildCheckPayload, buildPolicyPayload, classificationLabel, formatPassRateDrop } from "@/lib/regression-ui";

import { EvidenceBadge, Field } from "./shared";

export function RegressionsWorkspace() {
  const router = useRouter(); const search = useSearchParams();
  const [policies, setPolicies] = useState<RegressionPolicy[]>([]); const [checks, setChecks] = useState<RegressionCheckSummary[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [retry, setRetry] = useState(0);
  const [runId, setRunId] = useState(search.get("runId") ?? ""); const [policyId, setPolicyId] = useState(""); const [baseline, setBaseline] = useState<VariantKey | "">(""); const [candidate, setCandidate] = useState<VariantKey | "">("");
  const [policyFields, setPolicyFields] = useState({ name: "", description: "", minimumPassRateDrop: "", minimumSampleSize: "" }); const [policyErrors, setPolicyErrors] = useState<Record<string, string>>({});
  useEffect(() => { const controller = new AbortController(); Promise.all([listRegressionPolicies(controller.signal), listRegressionChecks({ signal: controller.signal })]).then(([policyPage, checkPage]) => { setPolicies(policyPage.items); setChecks(checkPage.items); setPolicyId((value) => value || policyPage.items[0]?.id || ""); setError(null); }).catch((reason: unknown) => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : "Unable to load regression evidence."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [retry]);
  async function savePolicy(event: React.FormEvent) { event.preventDefault(); const built = buildPolicyPayload(policyFields); setPolicyErrors(built.errors); if (Object.keys(built.errors).length) { setMessage("Review the highlighted policy fields."); return; } setBusy(true); setMessage(null); try { const created = await createRegressionPolicy(built.payload); setPolicies((items) => [created, ...items]); setPolicyId(created.id); setPolicyFields({ name: "", description: "", minimumPassRateDrop: "", minimumSampleSize: "" }); setMessage("Regression policy created."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Unable to create policy."); } finally { setBusy(false); } }
  async function saveCheck(event: React.FormEvent) { event.preventDefault(); const built = buildCheckPayload(runId, policyId, baseline, candidate); if (built.error || !built.payload) { setMessage(built.error); return; } setBusy(true); setMessage(null); try { const created = await createRegressionCheck(built.payload); router.push(`/regressions/${encodeURIComponent(created.id)}`); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Unable to create regression check."); } finally { setBusy(false); } }
  return <div className="mx-auto max-w-[90rem]"><PageHeader eyebrow="INVESTIGATE / REGRESSIONS" title="Regression evidence" description="Apply an explicit practical-drop policy to a completed experiment analysis, inspect canonical condition evidence, then plan and execute a frozen local Git bisection." />
    {message && <p role="status" aria-live="polite" className="mt-5 break-words border bg-surface p-4 text-sm">{message}</p>}
    {loading ? <div aria-busy="true" aria-label="Loading regression workspace" className="mt-7 h-96 animate-pulse border bg-surface" /> : error ? <div className="mt-7"><ViewState title="Couldn’t load regression evidence" detail={error} role="alert"><button type="button" onClick={() => { setLoading(true); setRetry((value) => value + 1); }} className={`mt-4 ${primaryButtonClass}`}>Retry</button></ViewState></div> : <div className="mt-7 grid gap-6 xl:grid-cols-2"><section aria-labelledby="policy-title" className="border bg-surface p-5"><h2 id="policy-title" className="text-xl font-semibold">Regression policies</h2><p className="mt-1 text-sm leading-6 text-muted">The practical pass-rate drop is the decision rule. A value of 0.05 means the candidate must fall by at least 5 percentage points.</p><form onSubmit={savePolicy} className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Policy name" error={policyErrors.name}><input value={policyFields.name} onChange={(event) => setPolicyFields({ ...policyFields, name: event.target.value })} maxLength={200} className={inputClass} /></Field><Field label="Minimum sample size" error={policyErrors.minimumSampleSize}><input type="number" min={1} max={1_000} value={policyFields.minimumSampleSize} onChange={(event) => setPolicyFields({ ...policyFields, minimumSampleSize: event.target.value })} className={inputClass} /></Field><Field label="Minimum pass-rate drop" hint="Fraction in (0, 1]." error={policyErrors.minimumPassRateDrop}><input type="number" min="0.000001" max="1" step="0.001" value={policyFields.minimumPassRateDrop} onChange={(event) => setPolicyFields({ ...policyFields, minimumPassRateDrop: event.target.value })} className={inputClass} /></Field><Field label="Description" error={policyErrors.description}><input value={policyFields.description} onChange={(event) => setPolicyFields({ ...policyFields, description: event.target.value })} maxLength={2_000} className={inputClass} /></Field><button disabled={busy} className={`sm:col-span-2 sm:justify-self-start ${primaryButtonClass}`}>Create policy</button></form>
      <ul className="mt-6 divide-y border" aria-label="Regression policies">{policies.map((policy) => <li key={policy.id} className="p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><h3 className="font-semibold">{policy.name}</h3><p className="mt-1 break-words text-sm text-muted">{policy.description || "No description"}</p></div><span className="font-mono text-xs">≥ {formatPassRateDrop(policy.minimum_pass_rate_drop)} · n ≥ {policy.minimum_sample_size}</span></div></li>)}</ul></section>
      <section aria-labelledby="check-title" className="border bg-surface p-5"><h2 id="check-title" className="text-xl font-semibold">Create regression check</h2><p className="mt-1 text-sm leading-6 text-muted">Use a completed experiment run with canonical analysis. A/B labels do not imply orientation; choose both roles explicitly.</p><form onSubmit={saveCheck} className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Completed experiment run ID"><input value={runId} onChange={(event) => setRunId(event.target.value)} required className={`${inputClass} font-mono`} /></Field><Field label="Regression policy"><select value={policyId} onChange={(event) => setPolicyId(event.target.value)} required className={inputClass}><option value="">Choose a policy</option>{policies.map((policy) => <option key={policy.id} value={policy.id}>{policy.name}</option>)}</select></Field><Field label="Baseline variant"><select value={baseline} onChange={(event) => setBaseline(event.target.value as VariantKey | "")} required className={inputClass}><option value="">Choose baseline</option><option value="A">Variant A</option><option value="B">Variant B</option></select></Field><Field label="Candidate variant"><select value={candidate} onChange={(event) => setCandidate(event.target.value as VariantKey | "")} required className={inputClass}><option value="">Choose candidate</option><option value="A">Variant A</option><option value="B">Variant B</option></select></Field><button disabled={busy || policies.length === 0} className={`sm:col-span-2 sm:justify-self-start ${primaryButtonClass}`}>Create regression check</button></form></section></div>}
    <section aria-labelledby="history-title" className="mt-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 id="history-title" className="text-xl font-semibold">Regression checks</h2><p className="mt-1 text-sm leading-6 text-muted">Immutable policy, orientation, provenance, and per-condition evidence.</p></div><span className="font-mono text-xs text-muted">{checks.length} LOADED</span></div>{checks.length === 0 ? <div className="mt-4"><ViewState title="No regression checks" detail="Create a policy and check from a completed experiment run." /></div> : <ul className="mt-4 space-y-3">{checks.map((check) => <li key={check.id} className="border bg-surface p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><Link href={`/regressions/${encodeURIComponent(check.id)}`} className="font-semibold text-accent hover:underline">{check.policy_name}</Link><p className="mt-1 break-all font-mono text-xs text-muted">{check.id}</p><p className="mt-2 text-sm">Baseline {check.baseline_variant} → candidate {check.candidate_variant}</p></div><EvidenceBadge value={check.classification} /></div><p className="mt-3 text-sm text-muted">{classificationLabel(check.classification)} using a {formatPassRateDrop(check.minimum_pass_rate_drop)} practical threshold.</p></li>)}</ul>}</section>
  </div>;
}
