import { apiBaseUrl } from "./api-base-url.ts";

export const REGRESSION_CLASSIFICATIONS = ["regression_detected", "no_regression_detected", "insufficient_evidence"] as const;
export const ANALYSIS_STATUSES = ["pending", "queued", "running", "waiting", "attributed", "inconclusive", "failed"] as const;
export const EXECUTION_OUTCOMES = ["pass", "regression", "indeterminate", "execution_failed"] as const;

export type VariantKey = "A" | "B";
export type RegressionClassification = (typeof REGRESSION_CLASSIFICATIONS)[number];
export type BisectionAnalysisStatus = (typeof ANALYSIS_STATUSES)[number];
export type ExecutionOutcome = (typeof EXECUTION_OUTCOMES)[number];
export type Page<T> = { items: T[]; has_more: boolean };

export type RegressionPolicy = { id: string; name: string; description: string | null; minimum_pass_rate_drop: number; minimum_sample_size: number; created_at: string };
export type RegressionFinding = {
  condition_position: number; analysis_id: string; definition_id: string; definition_name: string; evaluator_kind: string;
  evaluator_config: Record<string, unknown>; baseline_variant: VariantKey; candidate_variant: VariantKey; source_eligible: boolean;
  source_ineligible_reason: string | null; classification: RegressionClassification; minimum_pass_rate_drop: number; minimum_sample_size: number;
  sample_size: number | null; baseline_passed_count: number | null; candidate_passed_count: number | null; baseline_pass_rate: number | null;
  candidate_pass_rate: number | null; candidate_minus_baseline: number | null; both_passed_count: number | null; both_failed_count: number | null;
  baseline_only_passed_count: number | null; candidate_only_passed_count: number | null; discordant_count: number | null;
  matched_pairs_odds_ratio: number | null; p_value: number | null; rejects_null: boolean | null; source_interval_lower: number | null;
  source_interval_upper: number | null; confidence_interval_lower: number | null; confidence_interval_upper: number | null; created_at: string;
};
export type RegressionCheckSummary = {
  id: string; experiment_run_id: string; experiment_id: string; analysis_id: string; regression_policy_id: string;
  baseline_variant: VariantKey; candidate_variant: VariantKey; classification: RegressionClassification; policy_name: string;
  policy_description: string | null; minimum_pass_rate_drop: number; minimum_sample_size: number;
  baseline_provenance: Record<string, unknown>; candidate_provenance: Record<string, unknown>; created_at: string;
};
export type RegressionCheck = RegressionCheckSummary & { findings: RegressionFinding[] };
export type BisectionCommit = { position: number; commit_sha: string; committed_at: string; subject: string; parent_shas: string[] };
export type BisectionSessionSummary = {
  id: string; regression_check_id: string; repository_path: string;
  repository_fingerprint: string; repository_head_sha: string; baseline_revision: string; candidate_revision: string;
  baseline_commit_sha: string; candidate_commit_sha: string; baseline_provenance: Record<string, unknown>;
  candidate_provenance: Record<string, unknown>; commit_count: number; maximum_commit_count: number; status: "ready"; created_at: string;
};
export type BisectionSession = BisectionSessionSummary & { commits: BisectionCommit[] };
export type ProbeConfiguration = { executable: string; args: string[]; working_directory: string; timeout_seconds: number; max_stdout_bytes: number; max_stderr_bytes: number };
export type BisectionAnalysisStep = {
  sequence_number: number; good_position_before: number; good_commit_sha_before: string; bad_position_before: number; bad_commit_sha_before: string;
  selected_position: number; selected_commit_sha: string; evidence_source: "reused" | "requested"; execution_run_id: string;
  observed_outcome: ExecutionOutcome; decision: "confirm_candidate" | "advance_good" | "retreat_bad" | "skip_indeterminate" | "skip_execution_failed";
  good_position_after: number; good_commit_sha_after: string; bad_position_after: number; bad_commit_sha_after: string; created_at: string;
};
export type CommitSnapshot = { sha?: string; position?: number; committed_at?: string; subject?: string; parent_shas?: string[]; provenance?: Record<string, unknown>; [key: string]: unknown };
export type BisectionAnalysis = {
  id: string; session_id: string; status: BisectionAnalysisStatus; configuration_schema_version: "1"; configuration: ProbeConfiguration;
  repository_fingerprint: string; baseline_commit_sha: string; candidate_commit_sha: string; total_commit_count: number; current_interval_size: number;
  good_position: number; good_commit_sha: string; bad_position: number; bad_commit_sha: string; step_count: number; reused_evidence_count: number;
  new_evidence_count: number; usable_evidence_count: number; indeterminate_count: number; execution_failure_count: number;
  final_good_commit_sha: string | null; final_good_position: number | null; final_bad_commit_sha: string | null; final_bad_position: number | null;
  final_good_snapshot: CommitSnapshot | null; final_bad_snapshot: CommitSnapshot | null; terminal_reason: string | null; terminal_message: string | null;
  created_at: string; queued_at: string | null; started_at: string | null; completed_at: string | null; steps: BisectionAnalysisStep[];
};
export type ExecutionAttempt = { id: string; run_id: string; commit_sha: string; attempt_number: number; status: "running" | "completed" | "failed"; outcome: ExecutionOutcome | null; started_at: string; finished_at: string | null; exit_code: number | null; duration_ms: number | null; stdout: string; stderr: string; stdout_truncated: boolean; stderr_truncated: boolean; timed_out: boolean; failure_kind: string | null; failure_message: string | null; cleanup_failed: boolean; cleanup_message: string | null };
export type ExecutionTarget = {
  commit_sha: string; commit_position: number; status: "queued" | "running" | "completed" | "execution_failed"; outcome: ExecutionOutcome | null;
  attempt_count: number; started_at: string | null; finished_at: string | null; exit_code: number | null; duration_ms: number | null;
  stdout: string; stderr: string; stdout_truncated: boolean; stderr_truncated: boolean; timed_out: boolean; failure_kind: string | null;
  failure_message: string | null; cleanup_failed: boolean; cleanup_message: string | null; attempts: ExecutionAttempt[];
};
export type ExecutionRun = { id: string; session_id: string; status: "pending" | "queued" | "running" | "completed" | "failed"; configuration_schema_version: "1"; configuration: ProbeConfiguration; repository_fingerprint: string; planned_commit_count: number; requested_commit_count: number; completed_valid_count: number; regression_count: number; indeterminate_count: number; execution_failure_count: number; remaining_count: number; error_category: string | null; error_message: string | null; created_at: string; queued_at: string | null; started_at: string | null; completed_at: string | null; targets: ExecutionTarget[] };

export class RegressionApiError extends Error {
  readonly status: number;
  readonly code?: string;

  constructor(message: string, status: number, code?: string) {
    super(message);
    this.name = "RegressionApiError";
    this.status = status;
    this.code = code;
  }
}

export async function listRegressionPolicies(signal?: AbortSignal): Promise<Page<RegressionPolicy>> { return parsePage(await request("/api/v1/regression-policies?page_size=100", { signal }), parseRegressionPolicy); }
export async function createRegressionPolicy(payload: Omit<RegressionPolicy, "id" | "created_at">): Promise<RegressionPolicy> { return parseRegressionPolicy(await request("/api/v1/regression-policies", { method: "POST", body: payload })); }
export async function listRegressionChecks(options: { runId?: string; signal?: AbortSignal } = {}): Promise<Page<RegressionCheckSummary>> { const params = new URLSearchParams({ page_size: "100" }); if (options.runId) params.set("experiment_run_id", options.runId); return parsePage(await request(`/api/v1/regression-checks?${params}`, { signal: options.signal }), parseRegressionCheckSummary); }
export async function createRegressionCheck(payload: { experiment_run_id: string; regression_policy_id: string; baseline_variant: VariantKey; candidate_variant: VariantKey }): Promise<RegressionCheck> { return parseRegressionCheck(await request("/api/v1/regression-checks", { method: "POST", body: payload })); }
export async function getRegressionCheck(id: string, signal?: AbortSignal): Promise<RegressionCheck> { return parseRegressionCheck(await request(`/api/v1/regression-checks/${encodeURIComponent(id)}`, { signal })); }
export async function createBisectionSession(payload: { regression_check_id: string; repository_path: string }): Promise<BisectionSession> { return parseBisectionSession(await request("/api/v1/bisection-sessions", { method: "POST", body: payload })); }
export async function listBisectionSessions(checkId: string, signal?: AbortSignal): Promise<Page<BisectionSessionSummary>> { return parsePage(await request(`/api/v1/bisection-sessions?page_size=100&regression_check_id=${encodeURIComponent(checkId)}`, { signal }), parseBisectionSessionSummary); }
export async function getBisectionSession(id: string, signal?: AbortSignal): Promise<BisectionSession> { return parseBisectionSession(await request(`/api/v1/bisection-sessions/${encodeURIComponent(id)}`, { signal })); }
export async function createBisectionAnalysis(sessionId: string, configuration: ProbeConfiguration): Promise<BisectionAnalysis> { return parseBisectionAnalysis(await request(`/api/v1/bisection-sessions/${encodeURIComponent(sessionId)}/analyses`, { method: "POST", body: { configuration } })); }
export async function listBisectionAnalyses(sessionId: string, signal?: AbortSignal): Promise<Page<BisectionAnalysis>> { return parsePage(await request(`/api/v1/bisection-sessions/${encodeURIComponent(sessionId)}/analyses?page_size=100`, { signal }), parseBisectionAnalysis); }
export async function getBisectionAnalysis(id: string, signal?: AbortSignal): Promise<BisectionAnalysis> { return parseBisectionAnalysis(await request(`/api/v1/bisection-analyses/${encodeURIComponent(id)}`, { signal })); }
export async function startBisectionAnalysis(id: string): Promise<void> { await request(`/api/v1/bisection-analyses/${encodeURIComponent(id)}/execute`, { method: "POST" }); }
export async function listExecutionRuns(sessionId: string, signal?: AbortSignal): Promise<Page<ExecutionRun>> { return parsePage(await request(`/api/v1/bisection-sessions/${encodeURIComponent(sessionId)}/execution-runs?page_size=100`, { signal }), parseExecutionRun); }

export function parseRegressionCheck(value: unknown): RegressionCheck { const item = object(value); return { ...parseRegressionCheckSummary(item), findings: array(item.findings).map(parseRegressionFinding) }; }
export function parseBisectionAnalysis(value: unknown): BisectionAnalysis {
  const item = object(value);
  return { id: text(item.id), session_id: text(item.session_id), status: enumeration(item.status, ANALYSIS_STATUSES), configuration_schema_version: literal(item.configuration_schema_version, "1"), configuration: parseProbeConfiguration(item.configuration), repository_fingerprint: text(item.repository_fingerprint), baseline_commit_sha: text(item.baseline_commit_sha), candidate_commit_sha: text(item.candidate_commit_sha), total_commit_count: integer(item.total_commit_count), current_interval_size: integer(item.current_interval_size), good_position: integer(item.good_position), good_commit_sha: text(item.good_commit_sha), bad_position: integer(item.bad_position), bad_commit_sha: text(item.bad_commit_sha), step_count: integer(item.step_count), reused_evidence_count: integer(item.reused_evidence_count), new_evidence_count: integer(item.new_evidence_count), usable_evidence_count: integer(item.usable_evidence_count), indeterminate_count: integer(item.indeterminate_count), execution_failure_count: integer(item.execution_failure_count), final_good_commit_sha: nullableText(item.final_good_commit_sha), final_good_position: nullableInteger(item.final_good_position), final_bad_commit_sha: nullableText(item.final_bad_commit_sha), final_bad_position: nullableInteger(item.final_bad_position), final_good_snapshot: nullableObject(item.final_good_snapshot), final_bad_snapshot: nullableObject(item.final_bad_snapshot), terminal_reason: nullableText(item.terminal_reason), terminal_message: nullableText(item.terminal_message), created_at: text(item.created_at), queued_at: nullableText(item.queued_at), started_at: nullableText(item.started_at), completed_at: nullableText(item.completed_at), steps: array(item.steps).map(parseAnalysisStep) };
}

function parseRegressionPolicy(value: unknown): RegressionPolicy { const item = object(value); return { id: text(item.id), name: text(item.name), description: nullableText(item.description), minimum_pass_rate_drop: finite(item.minimum_pass_rate_drop), minimum_sample_size: integer(item.minimum_sample_size), created_at: text(item.created_at) }; }
function parseRegressionCheckSummary(value: unknown): RegressionCheckSummary { const item = object(value); return { id: text(item.id), experiment_run_id: text(item.experiment_run_id), experiment_id: text(item.experiment_id), analysis_id: text(item.analysis_id), regression_policy_id: text(item.regression_policy_id), baseline_variant: enumeration(item.baseline_variant, ["A", "B"] as const), candidate_variant: enumeration(item.candidate_variant, ["A", "B"] as const), classification: enumeration(item.classification, REGRESSION_CLASSIFICATIONS), policy_name: text(item.policy_name), policy_description: nullableText(item.policy_description), minimum_pass_rate_drop: finite(item.minimum_pass_rate_drop), minimum_sample_size: integer(item.minimum_sample_size), baseline_provenance: object(item.baseline_provenance), candidate_provenance: object(item.candidate_provenance), created_at: text(item.created_at) }; }
function parseRegressionFinding(value: unknown): RegressionFinding { const item = object(value); return { condition_position: integer(item.condition_position), analysis_id: text(item.analysis_id), definition_id: text(item.definition_id), definition_name: text(item.definition_name), evaluator_kind: text(item.evaluator_kind), evaluator_config: object(item.evaluator_config), baseline_variant: enumeration(item.baseline_variant, ["A", "B"] as const), candidate_variant: enumeration(item.candidate_variant, ["A", "B"] as const), source_eligible: bool(item.source_eligible), source_ineligible_reason: nullableText(item.source_ineligible_reason), classification: enumeration(item.classification, REGRESSION_CLASSIFICATIONS), minimum_pass_rate_drop: finite(item.minimum_pass_rate_drop), minimum_sample_size: integer(item.minimum_sample_size), sample_size: nullableInteger(item.sample_size), baseline_passed_count: nullableInteger(item.baseline_passed_count), candidate_passed_count: nullableInteger(item.candidate_passed_count), baseline_pass_rate: nullableFinite(item.baseline_pass_rate), candidate_pass_rate: nullableFinite(item.candidate_pass_rate), candidate_minus_baseline: nullableFinite(item.candidate_minus_baseline), both_passed_count: nullableInteger(item.both_passed_count), both_failed_count: nullableInteger(item.both_failed_count), baseline_only_passed_count: nullableInteger(item.baseline_only_passed_count), candidate_only_passed_count: nullableInteger(item.candidate_only_passed_count), discordant_count: nullableInteger(item.discordant_count), matched_pairs_odds_ratio: nullableFinite(item.matched_pairs_odds_ratio), p_value: nullableFinite(item.p_value), rejects_null: nullableBool(item.rejects_null), source_interval_lower: nullableFinite(item.source_interval_lower), source_interval_upper: nullableFinite(item.source_interval_upper), confidence_interval_lower: nullableFinite(item.confidence_interval_lower), confidence_interval_upper: nullableFinite(item.confidence_interval_upper), created_at: text(item.created_at) }; }
function parseBisectionSessionSummary(value: unknown): BisectionSessionSummary { const item = object(value); return { id: text(item.id), regression_check_id: text(item.regression_check_id), repository_path: text(item.repository_path), repository_fingerprint: text(item.repository_fingerprint), repository_head_sha: text(item.repository_head_sha), baseline_revision: text(item.baseline_revision), candidate_revision: text(item.candidate_revision), baseline_commit_sha: text(item.baseline_commit_sha), candidate_commit_sha: text(item.candidate_commit_sha), baseline_provenance: object(item.baseline_provenance), candidate_provenance: object(item.candidate_provenance), commit_count: integer(item.commit_count), maximum_commit_count: integer(item.maximum_commit_count), status: literal(item.status, "ready"), created_at: text(item.created_at) }; }
function parseBisectionSession(value: unknown): BisectionSession { const item = object(value); return { ...parseBisectionSessionSummary(item), commits: array(item.commits).map((raw) => { const commit = object(raw); return { position: integer(commit.position), commit_sha: text(commit.commit_sha), committed_at: text(commit.committed_at), subject: text(commit.subject), parent_shas: array(commit.parent_shas).map(text) }; }) }; }
function parseProbeConfiguration(value: unknown): ProbeConfiguration { const item = object(value); return { executable: text(item.executable), args: array(item.args).map(text), working_directory: text(item.working_directory), timeout_seconds: integer(item.timeout_seconds), max_stdout_bytes: integer(item.max_stdout_bytes), max_stderr_bytes: integer(item.max_stderr_bytes) }; }
function parseAnalysisStep(value: unknown): BisectionAnalysisStep { const item = object(value); return { sequence_number: integer(item.sequence_number), good_position_before: integer(item.good_position_before), good_commit_sha_before: text(item.good_commit_sha_before), bad_position_before: integer(item.bad_position_before), bad_commit_sha_before: text(item.bad_commit_sha_before), selected_position: integer(item.selected_position), selected_commit_sha: text(item.selected_commit_sha), evidence_source: enumeration(item.evidence_source, ["reused", "requested"] as const), execution_run_id: text(item.execution_run_id), observed_outcome: enumeration(item.observed_outcome, EXECUTION_OUTCOMES), decision: enumeration(item.decision, ["confirm_candidate", "advance_good", "retreat_bad", "skip_indeterminate", "skip_execution_failed"] as const), good_position_after: integer(item.good_position_after), good_commit_sha_after: text(item.good_commit_sha_after), bad_position_after: integer(item.bad_position_after), bad_commit_sha_after: text(item.bad_commit_sha_after), created_at: text(item.created_at) }; }
function parseExecutionRun(value: unknown): ExecutionRun { const item = object(value); return { id: text(item.id), session_id: text(item.session_id), status: enumeration(item.status, ["pending", "queued", "running", "completed", "failed"] as const), configuration_schema_version: literal(item.configuration_schema_version, "1"), configuration: parseProbeConfiguration(item.configuration), repository_fingerprint: text(item.repository_fingerprint), planned_commit_count: integer(item.planned_commit_count), requested_commit_count: integer(item.requested_commit_count), completed_valid_count: integer(item.completed_valid_count), regression_count: integer(item.regression_count), indeterminate_count: integer(item.indeterminate_count), execution_failure_count: integer(item.execution_failure_count), remaining_count: integer(item.remaining_count), error_category: nullableText(item.error_category), error_message: nullableText(item.error_message), created_at: text(item.created_at), queued_at: nullableText(item.queued_at), started_at: nullableText(item.started_at), completed_at: nullableText(item.completed_at), targets: array(item.targets).map(parseExecutionTarget) }; }
function parseExecutionTarget(value: unknown): ExecutionTarget { const item = object(value); return { commit_sha: text(item.commit_sha), commit_position: integer(item.commit_position), status: enumeration(item.status, ["queued", "running", "completed", "execution_failed"] as const), outcome: nullableEnum(item.outcome, EXECUTION_OUTCOMES), attempt_count: integer(item.attempt_count), started_at: nullableText(item.started_at), finished_at: nullableText(item.finished_at), exit_code: nullableInteger(item.exit_code), duration_ms: nullableInteger(item.duration_ms), stdout: text(item.stdout), stderr: text(item.stderr), stdout_truncated: bool(item.stdout_truncated), stderr_truncated: bool(item.stderr_truncated), timed_out: bool(item.timed_out), failure_kind: nullableText(item.failure_kind), failure_message: nullableText(item.failure_message), cleanup_failed: bool(item.cleanup_failed), cleanup_message: nullableText(item.cleanup_message), attempts: array(item.attempts).map(parseExecutionAttempt) }; }
function parseExecutionAttempt(value: unknown): ExecutionAttempt { const item = object(value); return { id: text(item.id), run_id: text(item.run_id), commit_sha: text(item.commit_sha), attempt_number: integer(item.attempt_number), status: enumeration(item.status, ["running", "completed", "failed"] as const), outcome: nullableEnum(item.outcome, EXECUTION_OUTCOMES), started_at: text(item.started_at), finished_at: nullableText(item.finished_at), exit_code: nullableInteger(item.exit_code), duration_ms: nullableInteger(item.duration_ms), stdout: text(item.stdout), stderr: text(item.stderr), stdout_truncated: bool(item.stdout_truncated), stderr_truncated: bool(item.stderr_truncated), timed_out: bool(item.timed_out), failure_kind: nullableText(item.failure_kind), failure_message: nullableText(item.failure_message), cleanup_failed: bool(item.cleanup_failed), cleanup_message: nullableText(item.cleanup_message) }; }

async function request(path: string, options: { method?: string; body?: unknown; signal?: AbortSignal } = {}): Promise<unknown> { const response = await fetch(`${apiBaseUrl}${path}`, { method: options.method ?? "GET", signal: options.signal, headers: { Accept: "application/json", ...(options.body === undefined ? {} : { "Content-Type": "application/json" }) }, body: options.body === undefined ? undefined : JSON.stringify(options.body) }); const raw: unknown = await response.json().catch(() => null); if (!response.ok) { const detail = raw && typeof raw === "object" && "detail" in raw ? object((raw as { detail: unknown }).detail) : {}; throw new RegressionApiError(typeof detail.message === "string" ? detail.message : "The regression service request failed.", response.status, typeof detail.code === "string" ? detail.code : undefined); } return raw; }
function parsePage<T>(value: unknown, parser: (value: unknown) => T): Page<T> { const item = object(value); return { items: array(item.items).map(parser), has_more: bool(item.has_more) }; }
function object(value: unknown): Record<string, unknown> { if (value === null || typeof value !== "object" || Array.isArray(value)) invalid(); return value as Record<string, unknown>; }
function nullableObject(value: unknown): Record<string, unknown> | null { return value === null ? null : object(value); }
function array(value: unknown): unknown[] { if (!Array.isArray(value)) invalid(); return value; }
function text(value: unknown): string { if (typeof value !== "string") invalid(); return value; }
function nullableText(value: unknown): string | null { return value === null ? null : text(value); }
function integer(value: unknown): number { if (typeof value !== "number" || !Number.isInteger(value)) invalid(); return value; }
function nullableInteger(value: unknown): number | null { return value === null ? null : integer(value); }
function finite(value: unknown): number { if (typeof value !== "number" || !Number.isFinite(value)) invalid(); return value; }
function nullableFinite(value: unknown): number | null { return value === null ? null : finite(value); }
function bool(value: unknown): boolean { if (typeof value !== "boolean") invalid(); return value; }
function nullableBool(value: unknown): boolean | null { return value === null ? null : bool(value); }
function enumeration<const T extends readonly string[]>(value: unknown, values: T): T[number] { const parsed = text(value); if (!values.includes(parsed)) invalid(); return parsed as T[number]; }
function nullableEnum<const T extends readonly string[]>(value: unknown, values: T): T[number] | null { return value === null ? null : enumeration(value, values); }
function literal<const T extends string>(value: unknown, expected: T): T { if (value !== expected) invalid(); return expected; }
function invalid(): never { throw new RegressionApiError("The regression service returned an unexpected response.", 502, "INVALID_RESPONSE"); }
